#!/usr/bin/env bash
# Install nginx and  return a page that contains the string 
# Hello World When querying Nginx at its root / with a GET request
sudo apt update -y
sudo apt install nginx -y
sudo nginx -s reload
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
