#!/usr/bin/env bash
#In this first task you need to configure web-02 to be identical to web-01
apt update -y
apt install nginx -y
sed -i "/listen \[::\]:80 default_server;/a\add_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
service nginx restart
