#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
apt-get update
apt-get install -y haproxy

echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 3560-web-01 34.75.209.112:80 check
	server 3560-web-02 34.139.115.250:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy start
